projects:
  globs:
    - "apps/*"
    - "packages/*"
  sources:
    repo: "."

vcs:
  client: "git"
  provider: "github"
  defaultBranch: "main"

pipeline:
  installDependencies: ["node"]

telemetry: false
